// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/system.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the phases of our MapReduce pipeline
type TaskType int32

const (
	TaskType_UNKNOWN TaskType = 0
	TaskType_MAP     TaskType = 1
	TaskType_REDUCE  TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MAP",
		2: "REDUCE",
	}
	TaskType_value = map[string]int32{
		"UNKNOWN": 0,
		"MAP":     1,
		"REDUCE":  2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_system_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_system_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{0}
}

// -----------------------------------------------------
// Message FROM: Executor (Worker)
// Message TO:   Coordinator (Master)
// -----------------------------------------------------
type ExecutorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecutorMessage_Register
	//	*ExecutorMessage_Result
	//	*ExecutorMessage_Heartbeat
	Payload       isExecutorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorMessage) Reset() {
	*x = ExecutorMessage{}
	mi := &file_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorMessage) ProtoMessage() {}

func (x *ExecutorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorMessage.ProtoReflect.Descriptor instead.
func (*ExecutorMessage) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorMessage) GetPayload() isExecutorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutorMessage) GetRegister() *RegistrationRequest {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ExecutorMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecutorMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ExecutorMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isExecutorMessage_Payload interface {
	isExecutorMessage_Payload()
}

type ExecutorMessage_Register struct {
	Register *RegistrationRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ExecutorMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecutorMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // NEW: Real-time telemetry
}

func (*ExecutorMessage_Register) isExecutorMessage_Payload() {}

func (*ExecutorMessage_Result) isExecutorMessage_Payload() {}

func (*ExecutorMessage_Heartbeat) isExecutorMessage_Payload() {}

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	AvailableRam  int64                  `protobuf:"varint,3,opt,name=available_ram,json=availableRam,proto3" json:"available_ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegistrationRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegistrationRequest) GetAvailableRam() int64 {
	if x != nil {
		return x.AvailableRam
	}
	return 0
}

// NEW: Sent periodically by the worker to prove it is alive
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=system.TaskType" json:"task_type,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	OutputData    []byte                 `protobuf:"bytes,5,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	ErrorLog      string                 `protobuf:"bytes,6,opt,name=error_log,json=errorLog,proto3" json:"error_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_UNKNOWN
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetOutputData() []byte {
	if x != nil {
		return x.OutputData
	}
	return nil
}

func (x *TaskResult) GetErrorLog() string {
	if x != nil {
		return x.ErrorLog
	}
	return ""
}

// -----------------------------------------------------
// Message FROM: Coordinator (Master)
// Message TO:   Executor (Worker)
// -----------------------------------------------------
type CoordinatorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_proto_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorMessage) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=system.TaskType" json:"task_type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	InputData     []byte                 `protobuf:"bytes,6,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_UNKNOWN
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Task) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

var File_proto_system_proto protoreflect.FileDescriptor

const file_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x12proto/system.proto\x12\x06system\"\xb8\x01\n" +
	"\x0fExecutorMessage\x129\n" +
	"\bregister\x18\x01 \x01(\v2\x1b.system.RegistrationRequestH\x00R\bregister\x12,\n" +
	"\x06result\x18\x02 \x01(\v2\x12.system.TaskResultH\x00R\x06result\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.system.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"t\n" +
	"\x13RegistrationRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12#\n" +
	"\ravailable_ram\x18\x03 \x01(\x03R\favailableRam\"(\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xc3\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12-\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\x10.system.TaskTypeR\btaskType\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1f\n" +
	"\voutput_data\x18\x05 \x01(\fR\n" +
	"outputData\x12\x1b\n" +
	"\terror_log\x18\x06 \x01(\tR\berrorLog\"6\n" +
	"\x12CoordinatorMessage\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.system.TaskR\x04task\"\xb2\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12-\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\x10.system.TaskTypeR\btaskType\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x1d\n" +
	"\n" +
	"input_data\x18\x06 \x01(\fR\tinputData*,\n" +
	"\bTaskType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03MAP\x10\x01\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x022[\n" +
	"\vCoordinator\x12L\n" +
	"\x11RegisterAndStream\x12\x17.system.ExecutorMessage\x1a\x1a.system.CoordinatorMessage(\x010\x01B\x13Z\x11dist-system/protob\x06proto3"

var (
	file_proto_system_proto_rawDescOnce sync.Once
	file_proto_system_proto_rawDescData []byte
)

func file_proto_system_proto_rawDescGZIP() []byte {
	file_proto_system_proto_rawDescOnce.Do(func() {
		file_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)))
	})
	return file_proto_system_proto_rawDescData
}

var file_proto_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_system_proto_goTypes = []any{
	(TaskType)(0),               // 0: system.TaskType
	(*ExecutorMessage)(nil),     // 1: system.ExecutorMessage
	(*RegistrationRequest)(nil), // 2: system.RegistrationRequest
	(*Heartbeat)(nil),           // 3: system.Heartbeat
	(*TaskResult)(nil),          // 4: system.TaskResult
	(*CoordinatorMessage)(nil),  // 5: system.CoordinatorMessage
	(*Task)(nil),                // 6: system.Task
}
var file_proto_system_proto_depIdxs = []int32{
	2, // 0: system.ExecutorMessage.register:type_name -> system.RegistrationRequest
	4, // 1: system.ExecutorMessage.result:type_name -> system.TaskResult
	3, // 2: system.ExecutorMessage.heartbeat:type_name -> system.Heartbeat
	0, // 3: system.TaskResult.task_type:type_name -> system.TaskType
	6, // 4: system.CoordinatorMessage.task:type_name -> system.Task
	0, // 5: system.Task.task_type:type_name -> system.TaskType
	1, // 6: system.Coordinator.RegisterAndStream:input_type -> system.ExecutorMessage
	5, // 7: system.Coordinator.RegisterAndStream:output_type -> system.CoordinatorMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_system_proto_init() }
func file_proto_system_proto_init() {
	if File_proto_system_proto != nil {
		return
	}
	file_proto_system_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecutorMessage_Register)(nil),
		(*ExecutorMessage_Result)(nil),
		(*ExecutorMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_proto_goTypes,
		DependencyIndexes: file_proto_system_proto_depIdxs,
		EnumInfos:         file_proto_system_proto_enumTypes,
		MessageInfos:      file_proto_system_proto_msgTypes,
	}.Build()
	File_proto_system_proto = out.File
	file_proto_system_proto_goTypes = nil
	file_proto_system_proto_depIdxs = nil
}
