// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.6
// source: proto/system.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Coordinator_RegisterAndStream_FullMethodName = "/system.Coordinator/RegisterAndStream"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The main service run by the Coordinator (Master)
type CoordinatorClient interface {
	// A bi-directional stream.
	// The Executor (Worker) calls this once to "check in" and
	// keeps the stream open to receive tasks and send results.
	RegisterAndStream(ctx context.Context, opts ...grpc.CallOption) (Coordinator_RegisterAndStreamClient, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) RegisterAndStream(ctx context.Context, opts ...grpc.CallOption) (Coordinator_RegisterAndStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Coordinator_ServiceDesc.Streams[0], Coordinator_RegisterAndStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &coordinatorRegisterAndStreamClient{ClientStream: stream}
	return x, nil
}

type Coordinator_RegisterAndStreamClient interface {
	Send(*ExecutorMessage) error
	Recv() (*CoordinatorMessage, error)
	grpc.ClientStream
}

type coordinatorRegisterAndStreamClient struct {
	grpc.ClientStream
}

func (x *coordinatorRegisterAndStreamClient) Send(m *ExecutorMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *coordinatorRegisterAndStreamClient) Recv() (*CoordinatorMessage, error) {
	m := new(CoordinatorMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility
//
// The main service run by the Coordinator (Master)
type CoordinatorServer interface {
	// A bi-directional stream.
	// The Executor (Worker) calls this once to "check in" and
	// keeps the stream open to receive tasks and send results.
	RegisterAndStream(Coordinator_RegisterAndStreamServer) error
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (UnimplementedCoordinatorServer) RegisterAndStream(Coordinator_RegisterAndStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterAndStream not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_RegisterAndStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServer).RegisterAndStream(&coordinatorRegisterAndStreamServer{ServerStream: stream})
}

type Coordinator_RegisterAndStreamServer interface {
	Send(*CoordinatorMessage) error
	Recv() (*ExecutorMessage, error)
	grpc.ServerStream
}

type coordinatorRegisterAndStreamServer struct {
	grpc.ServerStream
}

func (x *coordinatorRegisterAndStreamServer) Send(m *CoordinatorMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *coordinatorRegisterAndStreamServer) Recv() (*ExecutorMessage, error) {
	m := new(ExecutorMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterAndStream",
			Handler:       _Coordinator_RegisterAndStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/system.proto",
}
